### PR TITLE
Set of support

### PR DESCRIPTION
**Pull request by anitha-cs**
John, 
  I merged of my set of support changes with the latest code from your develop branch. Let me know if this works.

Anitha.

### CODE REVIEW

**Comment by backesj** [comment]
I'm in the process of merging this. Should be done early tomorrow.

**Comment by anitha-cs** [comment]
John,
   I am getting a lot of "closed" emails..... Does this mean anything for
me?? or it is just a indicator that you are looking at the request?

Anitha.

On Mon, Apr 25, 2016 at 4:55 PM, John Backes <notifications@github.com>
wrote:

> I'm in the process of merging this. Should be done early tomorrow.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smaccm/smaccm/pull/47#issuecomment-214539500>
>



-- 
Regards

*,Anitha M----------------*

**Comment by anitha-cs** [comment]
By the way, I sent a request to pull the change to your develop branch - is
that what you are doing or will it be a newer branch?

Anitha.

On Mon, Apr 25, 2016 at 4:58 PM, Anitha Murugesan <
murugesan.anitha@gmail.com> wrote:

> John,
>    I am getting a lot of "closed" emails..... Does this mean anything for
> me?? or it is just a indicator that you are looking at the request?
>
> Anitha.
>
> On Mon, Apr 25, 2016 at 4:55 PM, John Backes <notifications@github.com>
> wrote:
>
>> I'm in the process of merging this. Should be done early tomorrow.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smaccm/smaccm/pull/47#issuecomment-214539500>
>>
>
>
>
> --
> Regards
>
> *,Anitha M----------------*
>



-- 
Regards

*,Anitha M----------------*

**Comment by backesj** [comment]
I'm merging your pull request. There were some other outstanding requests
in there that I removed.

- John

**Comment by backesj** [comment]
It will be pushed to the develop branch tomorrow.

- John

**Pull request closed without merging**
